# ══════════════════════════════════════════════
#  Foot Terminal — Material You Dynamic Colors
# ══════════════════════════════════════════════

[main]
include=~/.config/foot/colors.ini
font=JetBrainsMono Nerd Font Mono:size=28
font-bold=JetBrainsMono Nerd Font Mono:size=28:weight=bold
font-italic=JetBrainsMono Nerd Font Mono:size=28:slant=italic
font-bold-italic=JetBrainsMono Nerd Font Mono:size=28:weight=bold:slant=italic
pad=30x30 center
dpi-aware=yes
initial-window-size-pixels=1600x900
selection-target=both
bold-text-in-bright=yes
underline-thickness=2px

[bell]
urgent=no
notify=no
visual=no

[cursor]
style=beam
blink=yes
beam-thickness=2

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[url]
launch=xdg-open ${url}

[scrollback]
lines=10000
multiplier=3.0
indicator-position=relative

[csd]
preferred=none
size=0

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
font-increase=Control+plus Control+equal
font-decrease=Control+minus
font-reset=Control+0
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
search-start=Control+Shift+f
